import { defineConfig, devices } from '@playwright/test';

// Prod-only config: exercises a real `vite build` output (hashed /_app/immutable/assets/*
// URLs, the Cloudflare adapter's autogenerated immutable Cache-Control header) instead of
// the dev server that playwright.config.ts uses. See tests/asset-caching.prod.spec.ts.
export default defineConfig({
	testDir: './tests',
	testMatch: /\.prod\.spec\.ts$/,
	fullyParallel: true,
	forbidOnly: !!process.env.CI,
	retries: process.env.CI ? 2 : 0,
	workers: process.env.CI ? 1 : undefined,
	reporter: 'line',
	use: {
		baseURL: 'http://localhost:4173',
		trace: 'on-first-retry'
	},
	projects: [
		{
			name: 'chromium',
			use: { ...devices['Desktop Chrome'] }
		}
	],
	webServer: {
		command: 'bun run build && bun run preview',
		port: 4173,
		reuseExistingServer: !process.env.CI,
		timeout: 180_000
	}
});
