import { test, expect } from '@playwright/test';

/**
 * Prod-only checks for the `hashed-assets-static-env` change.
 *
 * Runs via `bun run test:e2e:prod` (playwright.prod.config.ts), which builds the site
 * (`bun run build`) and serves the real output (`bun run preview`, port 4173). This is the
 * ONLY spec that can assert hashed `/_app/immutable/assets/*` URLs and the Cloudflare
 * adapter's autogenerated immutable Cache-Control header, since the default dev-server
 * config (playwright.config.ts, `bun run dev`) never produces either.
 *
 * Does NOT re-assert og:image/twitter:image (already covered, unchanged, by
 * tests/opengraph.spec.ts) to avoid duplicate coverage.
 *
 * `/_app/env.js` absence (spec: "Public Environment Configuration") is ALSO verified only
 * here, not in the dev-compatible spec, despite tasks.md placing it there too. Verified
 * empirically while writing this spec: a hard `page.goto()` never fetches `/_app/env.js` on
 * first load in either dev or prod, even with the pre-fix `$env/dynamic/public` imports,
 * because SvelteKit inlines the dynamic-public-env value into the SSR'd page's own data on
 * the FIRST load of a route. The endpoint is only fetched on a CLIENT-SIDE navigation into a
 * route whose rendered component reads `$env/dynamic/public` (confirmed by direct
 * `curl localhost:5173/_app/env.js` returning 200, and by instrumented spikes: a hard load
 * to /contact/ captures zero /_app/ requests for it, while home -> click -> /contact/ does).
 * The spec's own scenarios are scoped to "a production build served via preview or
 * deployment" anyway, so this is where the real signal belongs; the dev spec's copy of this
 * check is kept as a harmless (always-passing) smoke check, matching the Test B/C precedent
 * already documented in tasks.md.
 */

// Vite's actual output naming is `[name].[hash].[ext]` (e.g.
// `/_app/immutable/assets/hero-stage-400.qAEnGabw.webp`), not `[name]-[hash].[ext]`.
const HASHED_ASSET_PATTERN = /^\/_app\/immutable\/assets\/[^/]+\.[\w-]{6,}\.(webp|svg)$/;

// srcset-derived URLs come back with a full origin (browser-serialized attribute); plain
// `src` attributes come back root-relative. Normalize both to a path before matching/fetching.
const toPath = (url: string): string => new URL(url, 'http://localhost:4173').pathname;

test.describe('no /_app/env.js request (production build, client-side navigation)', () => {
	test('navigating client-side into the contact page never fetches /_app/env.js', async ({ page }) => {
		const urls: string[] = [];
		page.on('request', (request) => urls.push(request.url()));

		await page.goto('/');
		await page.waitForLoadState('networkidle');
		await page.locator('a[href="/contact/"]').first().click();
		await page.waitForURL('**/contact/');
		await page.waitForTimeout(2000);

		expect(urls.filter((url) => url.includes('/_app/env.js'))).toEqual([]);
	});

	test('navigating client-side into a package page (LeadForm) never fetches /_app/env.js', async ({ page }) => {
		const urls: string[] = [];
		page.on('request', (request) => urls.push(request.url()));

		// Two client-side hops (home -> listing -> detail): no direct link to a package
		// detail page exists on the home page itself.
		await page.goto('/');
		await page.waitForLoadState('networkidle');
		await page.locator('a[href="/packages/"]').first().click();
		await page.waitForURL('**/packages/');
		await page.waitForLoadState('networkidle');
		await page.locator('a[href="/packages/eco/"]').first().click();
		await page.waitForURL('**/packages/eco/');
		await page.waitForTimeout(2000);

		expect(urls.filter((url) => url.includes('/_app/env.js'))).toEqual([]);
	});

	test('the home page issues no request to /_app/env.js', async ({ page }) => {
		const urls: string[] = [];
		page.on('request', (request) => urls.push(request.url()));

		await page.goto('/');
		await page.waitForLoadState('networkidle');

		expect(urls.filter((url) => url.includes('/_app/env.js'))).toEqual([]);
	});
});

test.describe('asset caching (production build)', () => {
	test('the 5 hashed hero/logo assets resolve under /_app/immutable/assets/ and get an immutable cache header', async ({
		page,
		request
	}) => {
		await page.goto('/');
		await page.waitForLoadState('networkidle');

		const heroImgSrc = await page.locator('img[alt*="stage"]').first().getAttribute('src');
		const heroSrcset = await page.locator('img[alt*="stage"]').first().getAttribute('srcset');
		expect(heroSrcset).not.toBeNull();

		const srcsetUrls = (heroSrcset ?? '')
			.split(',')
			.map((entry) => toPath(entry.trim().split(/\s+/)[0]))
			.filter(Boolean);

		const logoSrc = await page.locator('header img[alt]').first().getAttribute('src');

		expect(heroImgSrc).not.toBeNull();
		expect(logoSrc).not.toBeNull();

		// 3 hashed hero variants (400/512/mobile) + 1 literal /hero-stage.webp entry.
		expect(srcsetUrls.length).toBe(4);
		const hashedHeroUrls = srcsetUrls.filter((url) => url !== '/hero-stage.webp');
		expect(hashedHeroUrls.length).toBe(3);

		const hashedUrls = [...hashedHeroUrls, toPath(logoSrc as string)];
		expect(hashedUrls.length).toBe(4);

		for (const url of hashedUrls) {
			expect(url, `${url} should match the hashed Vite asset URL format`).toMatch(HASHED_ASSET_PATTERN);
		}

		for (const url of hashedUrls) {
			const response = await request.get(url);
			expect(response.status()).toBe(200);
			expect(response.headers()['cache-control']).toBe('public, immutable, max-age=31536000');
		}
	});

	test('the footer logo pair also resolves to hashed, immutably-cached assets', async ({ page, request }) => {
		await page.goto('/');
		await page.waitForLoadState('networkidle');

		const footerLogos = page.locator('footer img[alt]');
		const count = await footerLogos.count();
		expect(count).toBeGreaterThanOrEqual(2);

		const urls = new Set<string>();
		for (let i = 0; i < count; i++) {
			const src = await footerLogos.nth(i).getAttribute('src');
			if (src) urls.add(toPath(src));
		}

		expect(urls.size).toBeGreaterThanOrEqual(1);

		for (const url of urls) {
			expect(url, `${url} should match the hashed Vite asset URL format`).toMatch(HASHED_ASSET_PATTERN);
			const response = await request.get(url);
			expect(response.status()).toBe(200);
			expect(response.headers()['cache-control']).toBe('public, immutable, max-age=31536000');
		}
	});
});
