import { test, expect } from '@playwright/test';

/**
 * Prod-only checks for the `hashed-assets-static-env` change, extended by the
 * `hashed-package-image-variants` change (package image variants describe block below) to
 * cover the same mechanism for package thumb/mobile/desktop images and the two dual-use
 * assets (hero-stage.webp 1024w, equipment page mice.webp desktop).
 *
 * Runs via `bun run test:e2e:prod` (playwright.prod.config.ts), which builds the site
 * (`bun run build`) and serves the real output (`bun run preview`, port 4173). This is the
 * ONLY spec that can assert hashed `/_app/immutable/assets/*` URLs and the Cloudflare
 * adapter's autogenerated immutable Cache-Control header, since the default dev-server
 * config (playwright.config.ts, `bun run dev`) never produces either.
 *
 * Does NOT re-assert og:image/twitter:image (already covered, unchanged, by
 * tests/opengraph.spec.ts) to avoid duplicate coverage.
 *
 * `/_app/env.js` absence (spec: "Public Environment Configuration") is ALSO verified only
 * here, not in the dev-compatible spec, despite tasks.md placing it there too. Verified
 * empirically while writing this spec: a hard `page.goto()` never fetches `/_app/env.js` on
 * first load in either dev or prod, even with the pre-fix `$env/dynamic/public` imports,
 * because SvelteKit inlines the dynamic-public-env value into the SSR'd page's own data on
 * the FIRST load of a route. The endpoint is only fetched on a CLIENT-SIDE navigation into a
 * route whose rendered component reads `$env/dynamic/public` (confirmed by direct
 * `curl localhost:5173/_app/env.js` returning 200, and by instrumented spikes: a hard load
 * to /contact/ captures zero /_app/ requests for it, while home -> click -> /contact/ does).
 * The spec's own scenarios are scoped to "a production build served via preview or
 * deployment" anyway, so this is where the real signal belongs; the dev spec's copy of this
 * check is kept as a harmless (always-passing) smoke check, matching the Test B/C precedent
 * already documented in tasks.md.
 */

// Vite's actual output naming is `[name].[hash].[ext]` (e.g.
// `/_app/immutable/assets/hero-stage-400.qAEnGabw.webp`), not `[name]-[hash].[ext]`.
const HASHED_ASSET_PATTERN = /^\/_app\/immutable\/assets\/[^/]+\.[\w-]{6,}\.(webp|svg)$/;

// srcset-derived URLs come back with a full origin (browser-serialized attribute); plain
// `src` attributes come back root-relative. Normalize both to a path before matching/fetching.
const toPath = (url: string): string => new URL(url, 'http://localhost:4173').pathname;

test.describe('no /_app/env.js request (production build, client-side navigation)', () => {
	test('navigating client-side into the contact page never fetches /_app/env.js', async ({ page }) => {
		const urls: string[] = [];
		page.on('request', (request) => urls.push(request.url()));

		await page.goto('/');
		await page.waitForLoadState('networkidle');
		await page.locator('a[href="/contact/"]').first().click();
		await page.waitForURL('**/contact/');
		await page.waitForTimeout(2000);

		expect(urls.filter((url) => url.includes('/_app/env.js'))).toEqual([]);
	});

	test('navigating client-side into a package page (LeadForm) never fetches /_app/env.js', async ({ page }) => {
		const urls: string[] = [];
		page.on('request', (request) => urls.push(request.url()));

		// Two client-side hops (home -> listing -> detail): no direct link to a package
		// detail page exists on the home page itself.
		await page.goto('/');
		await page.waitForLoadState('networkidle');
		await page.locator('a[href="/packages/"]').first().click();
		await page.waitForURL('**/packages/');
		await page.waitForLoadState('networkidle');
		await page.locator('a[href="/packages/eco/"]').first().click();
		await page.waitForURL('**/packages/eco/');
		await page.waitForTimeout(2000);

		expect(urls.filter((url) => url.includes('/_app/env.js'))).toEqual([]);
	});

	test('the home page issues no request to /_app/env.js', async ({ page }) => {
		const urls: string[] = [];
		page.on('request', (request) => urls.push(request.url()));

		await page.goto('/');
		await page.waitForLoadState('networkidle');

		expect(urls.filter((url) => url.includes('/_app/env.js'))).toEqual([]);
	});
});

test.describe('asset caching (production build)', () => {
	test('the 5 hashed hero/logo assets resolve under /_app/immutable/assets/ and get an immutable cache header', async ({
		page,
		request
	}) => {
		await page.goto('/');
		await page.waitForLoadState('networkidle');

		const heroImgSrc = await page.locator('img[alt*="stage"]').first().getAttribute('src');
		const heroSrcset = await page.locator('img[alt*="stage"]').first().getAttribute('srcset');
		expect(heroSrcset).not.toBeNull();

		const srcsetUrls = (heroSrcset ?? '')
			.split(',')
			.map((entry) => toPath(entry.trim().split(/\s+/)[0]))
			.filter(Boolean);

		const logoSrc = await page.locator('header img[alt]').first().getAttribute('src');

		expect(heroImgSrc).not.toBeNull();
		expect(logoSrc).not.toBeNull();

		// 4 hashed hero variants (400/512/mobile/1024, the 1024w now a Bucket-2 dual-use copy).
		expect(srcsetUrls.length).toBe(4);

		const hashedUrls = [...srcsetUrls, toPath(logoSrc as string)];
		expect(hashedUrls.length).toBe(5);

		for (const url of hashedUrls) {
			expect(url, `${url} should match the hashed Vite asset URL format`).toMatch(HASHED_ASSET_PATTERN);
		}

		for (const url of hashedUrls) {
			const response = await request.get(url);
			expect(response.status()).toBe(200);
			expect(response.headers()['cache-control']).toBe('public, immutable, max-age=31536000');
		}
	});

	test('the footer logo pair also resolves to hashed, immutably-cached assets', async ({ page, request }) => {
		await page.goto('/');
		await page.waitForLoadState('networkidle');

		const footerLogos = page.locator('footer img[alt]');
		const count = await footerLogos.count();
		expect(count).toBeGreaterThanOrEqual(2);

		const urls = new Set<string>();
		for (let i = 0; i < count; i++) {
			const src = await footerLogos.nth(i).getAttribute('src');
			if (src) urls.add(toPath(src));
		}

		expect(urls.size).toBeGreaterThanOrEqual(1);

		for (const url of urls) {
			expect(url, `${url} should match the hashed Vite asset URL format`).toMatch(HASHED_ASSET_PATTERN);
			const response = await request.get(url);
			expect(response.status()).toBe(200);
			expect(response.headers()['cache-control']).toBe('public, immutable, max-age=31536000');
		}
	});
});

/**
 * Package image variants (`hashed-package-image-variants` change). Reads <source>/<img>
 * attributes directly via locator rather than relying on which <picture> source the
 * browser's viewport actually picks, since Playwright's default viewport may not match
 * either media query breakpoint.
 */
async function expectHashedAndImmutable(
	request: import('@playwright/test').APIRequestContext,
	url: string
): Promise<void> {
	expect(url, `${url} should match the hashed Vite asset URL format`).toMatch(HASHED_ASSET_PATTERN);
	const response = await request.get(url);
	expect(response.status()).toBe(200);
	expect(response.headers()['cache-control']).toBe('public, immutable, max-age=31536000');
}

test.describe('package image variants (production build)', () => {
	test('a blog post PostCTA thumb resolves to a hashed, immutably-cached asset', async ({ page, request }) => {
		await page.goto('/blog/weather-considerations-for-outdoor-rentals/');
		await page.waitForLoadState('networkidle');

		const thumbSrc = await page.locator('[data-testid="post-cta"] img').first().getAttribute('src');
		expect(thumbSrc).not.toBeNull();

		await expectHashedAndImmutable(request, toPath(thumbSrc as string));
	});

	test('every thumb srcset candidate (96w and 160w) is a hashed file, never an inlined data URI', async ({
		page,
		request
	}) => {
		// 4 de las 5 thumb-sm pesan menos de 4 KiB: sin el assetsInlineLimit de vite.config.ts
		// Vite las inlinea como base64 y cada una se repite en el HTML de cada post.
		const response = await page.goto('/blog/weather-considerations-for-outdoor-rentals/');
		const html = (await response?.text()) ?? '';
		expect(html).not.toContain('data:image/');

		for (const selector of ['img.post-cta-img', 'img.packages-rail-img']) {
			const srcset = (await page.locator(selector).first().getAttribute('srcset')) ?? '';
			const urls = srcset.split(',').map((c) => c.trim().split(/\s+/)[0]);
			expect(urls, `${selector} srcset`).toHaveLength(2);
			for (const url of urls) await expectHashedAndImmutable(request, toPath(url));
		}
	});

	test('/packages/ mobile and desktop variants resolve to hashed, immutably-cached assets', async ({
		page,
		request
	}) => {
		await page.goto('/packages/');
		await page.waitForLoadState('networkidle');

		const card = page.locator('[data-testid="package-card"]').first();
		const mobileSrcset = await card.locator('source[media="(max-width: 767px)"]').getAttribute('srcset');
		const desktopSrcset = await card.locator('source[media="(min-width: 768px)"]').getAttribute('srcset');
		expect(mobileSrcset).not.toBeNull();
		expect(desktopSrcset).not.toBeNull();

		await expectHashedAndImmutable(request, toPath(mobileSrcset as string));
		await expectHashedAndImmutable(request, toPath(desktopSrcset as string));
	});

	test('/packages/eco/ mobile and desktop variants resolve to hashed, immutably-cached assets', async ({
		page,
		request
	}) => {
		await page.goto('/packages/eco/');
		await page.waitForLoadState('networkidle');

		const mobileSrcset = await page
			.locator('source[media="(max-width: 767px)"]')
			.first()
			.getAttribute('srcset');
		const desktopSrcset = await page
			.locator('source[media="(min-width: 768px)"]')
			.first()
			.getAttribute('srcset');
		expect(mobileSrcset).not.toBeNull();
		expect(desktopSrcset).not.toBeNull();

		await expectHashedAndImmutable(request, toPath(mobileSrcset as string));
		await expectHashedAndImmutable(request, toPath(desktopSrcset as string));
	});

	test('/equipment/ mobile (Bucket 1) and desktop (Bucket 2 dual-use) variants resolve to hashed, immutably-cached assets', async ({
		page,
		request
	}) => {
		await page.goto('/equipment/');
		await page.waitForLoadState('networkidle');

		const mobileSrcset = await page
			.locator('source[media="(max-width: 1023px)"]')
			.first()
			.getAttribute('srcset');
		const desktopSrcset = await page
			.locator('source[media="(min-width: 1024px)"]')
			.first()
			.getAttribute('srcset');
		const desktopImgSrc = await page
			.locator('img[alt="MICE Audiovisual Pack Setup for Meetings"]')
			.first()
			.getAttribute('src');
		expect(mobileSrcset).not.toBeNull();
		expect(desktopSrcset).not.toBeNull();
		expect(desktopImgSrc).not.toBeNull();

		await expectHashedAndImmutable(request, toPath(mobileSrcset as string));
		await expectHashedAndImmutable(request, toPath(desktopSrcset as string));
		await expectHashedAndImmutable(request, toPath(desktopImgSrc as string));
	});
});
