/**
 * Blog data layer — public API.
 *
 * All data is read at build time via import.meta.glob (eager).
 * No Node built-ins are used (Cloudflare adapter compatible).
 *
 * Pure pipeline logic lives in blog-pipeline.ts (testable independently).
 */
import type { BlogPost, Category, Author } from '$lib/types/blog';
import {
	buildPostsFromGlob,
	getCategoriesFromPosts,
	getPostsByCategoryFromPosts,
	getAuthorsFromPosts,
	getPostsByAuthorFromPosts,
	getNewsPosts as getNewsPostsFromPosts,
	getArticlePosts as getArticlePostsFromPosts,
	buildLocalizedPosts,
	getLocalizedCategoriesFromPosts
} from '$lib/data/blog-pipeline';
import type { Locale } from '$lib/i18n/locales';
import { loadContentMap } from '$lib/i18n/router';
import coverThumbsRaw from '$lib/data/cover-thumbs.json';
import postFaqsRaw from '$lib/data/post-faqs.json';
import postTocRaw from '$lib/data/post-toc.json';
import blogMeta from 'virtual:blog-meta';
import translationLoaders, { builtAt } from 'virtual:blog-translations';

const coverThumbs = coverThumbsRaw as Record<
	string,
	{ thumb: string; srcset?: string; width?: number; height?: number }
>;
const postFaqs = postFaqsRaw as Record<string, { question: string; answer: string }[]>;
const postToc = postTocRaw as Record<string, { id: string; text: string; level: 2 | 3 }[]>;

// ─── Build-time data load ─────────────────────────────────────────────────────

// Frontmatter ONLY — provided by the `virtual:blog-meta` Vite plugin, which parses the
// YAML frontmatter from the raw .svx files at build time (scripts/vite-blog-meta.mjs).
// Crucially this does NOT statically import the compiled .svx, so the lazy component glob
// below can code-split each post body into its own chunk. (A previous eager
// `import.meta.glob(..., { import: 'metadata' })` defeated that splitting, bundling every
// post body into one ~3.4 MB chunk loaded even on listing pages — a CWV regression.)
const metaModules = blogMeta as Record<string, { metadata: unknown }>;

// Compiled components — LAZY loaders, code-split per post. Only the visited post's
// body chunk is fetched (in [slug]/+page.ts via getPostComponentLoader).
const componentLoaders = import.meta.glob('../../content/blog/*.svx', {
	import: 'default'
}) as Record<string, () => Promise<unknown>>;

// Posts cache — computed once at module evaluation time (ADR-003, ADR-004).
// The date filter uses the current date at build time (ADR-004).
const _allPosts: BlogPost[] = buildPostsFromGlob(metaModules);

// Attach the card-sized cover variant (~768px) from the generated lookup, so listing
// grids serve a card-appropriate image instead of the full-size cover (CWV / LCP).
// Also attach FAQ pairs and cover thumbs in one pass.
for (const post of _allPosts) {
	const info = coverThumbs[post.coverImage];
	post.coverImageThumb = info?.thumb ?? post.coverImage;
	post.coverImageSrcset = info?.srcset;
	post.coverImageWidth = info?.width;
	post.coverImageHeight = info?.height;

	// Attach pre-extracted FAQ pairs (generated by scripts/gen-post-faqs.ts).
	const faqs = postFaqs[post.slug];
	if (faqs && faqs.length > 0) {
		post.faqs = faqs;
	}

	// Attach pre-extracted ToC entries (generated by scripts/gen-post-toc.ts).
	const toc = postToc[post.slug];
	if (toc && toc.length > 0) {
		post.toc = toc;
	}
}

// Taxonomy caches
const _categories: Category[] = getCategoriesFromPosts(_allPosts);
const _authors: Author[] = getAuthorsFromPosts(_allPosts);

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Returns all published, non-draft posts sorted by publishDate descending.
 */
export function getAllPosts(): BlogPost[] {
	return _allPosts;
}

/**
 * @deprecated Use getAllPosts() — kept for spec compatibility (SC-BC spec references getPosts()).
 */
export function getPosts(): BlogPost[] {
	return _allPosts;
}

/**
 * Returns a single post by slug, or undefined if not found.
 */
export function getPostBySlug(slug: string): BlogPost | undefined {
	return _allPosts.find((p) => p.slug === slug);
}

/**
 * @deprecated Use getPostBySlug() — kept for spec compatibility.
 */
export function getPost(slug: string): BlogPost | undefined {
	return getPostBySlug(slug);
}

/**
 * Returns all slugs of published posts (used by entries generators).
 */
export function getPostSlugs(): string[] {
	return _allPosts.map((p) => p.slug);
}

/**
 * Returns deduplicated categories derived from published posts, sorted alphabetically.
 */
export function getCategories(): Category[] {
	return _categories;
}

/**
 * Returns published posts in the given category slug.
 * Returns an empty array if the category does not exist or has no posts.
 */
export function getPostsByCategory(categorySlug: string): BlogPost[] {
	return getPostsByCategoryFromPosts(_allPosts, categorySlug);
}

/**
 * Returns deduplicated authors derived from published posts, sorted alphabetically.
 */
export function getAuthors(): Author[] {
	return _authors;
}

/**
 * Returns published posts by the given author slug.
 * Returns an empty array if the author does not exist or has no posts.
 */
export function getPostsByAuthor(authorSlug: string): BlogPost[] {
	return getPostsByAuthorFromPosts(_allPosts, authorSlug);
}

/**
 * Returns published posts in the "News" category (isNews === true).
 */
export function getNewsPosts(): BlogPost[] {
	return getNewsPostsFromPosts(_allPosts);
}

/**
 * Returns published non-news posts (isNews === false).
 */
export function getArticlePosts(): BlogPost[] {
	return getArticlePostsFromPosts(_allPosts);
}

/**
 * Returns the lazy loader for a post's compiled mdsvex component, or undefined.
 * Used by /blog/[slug]/+page.ts to fetch ONLY the visited post's body chunk.
 */
export function getPostComponentLoader(slug: string): (() => Promise<unknown>) | undefined {
	const entry = Object.entries(componentLoaders).find(
		([path]) => path.split('/').pop()?.replace(/\.svx$/, '') === slug
	);
	return entry?.[1];
}

// ─── Fase 4: posts per locale ─────────────────────────────────────────────────
//
// A translation lives at src/content/blog/<locale>/<en-slug>.svx. Its frontmatter, FAQ and ToC
// come from `virtual:blog-translations`, one lazy chunk per locale, so a page never downloads
// the other languages. That makes the per locale API async. For 'en' it returns the English
// data above, unchanged. Posts keep the ENGLISH slug (their identity), `url` is localized.

// Compiled translated bodies, lazy and code split per post like the English ones. The English
// glob above (`*.svx`) only matches the root folder, so it never picks a translation up.
const translatedComponentLoaders = import.meta.glob('../../content/blog/*/*.svx', {
	import: 'default'
}) as Record<string, () => Promise<unknown>>;

export interface LocaleBlog {
	posts: BlogPost[];
	categories: Category[];
	authors: Author[];
}

const localeBlogs = new Map<Locale, Promise<LocaleBlog>>();

function loadLocaleBlog(locale: Locale): Promise<LocaleBlog> {
	if (locale === 'en') return Promise.resolve({ posts: _allPosts, categories: _categories, authors: _authors });
	let cached = localeBlogs.get(locale);
	if (!cached) {
		const loader = translationLoaders[locale];
		cached = Promise.all([loader ? loader() : Promise.resolve({}), loadContentMap(locale)]).then(
			([translations, map]) => {
				// The build time cut, the same one the availability sets were computed with, so
				// a listing never shows a post whose URL was not built.
				const posts = buildLocalizedPosts(locale, _allPosts, translations, map, new Date(builtAt));
				return {
					posts,
					categories: getLocalizedCategoriesFromPosts(posts, map),
					authors: getAuthorsFromPosts(posts)
				};
			}
		);
		localeBlogs.set(locale, cached);
	}
	return cached;
}

/** A locale's published posts, categories and authors in one call (locale sitemaps). */
export function getBlogForLocale(locale: Locale): Promise<LocaleBlog> {
	return loadLocaleBlog(locale);
}

/** Published posts of a locale, newest first. English: getAllPosts(). */
export async function getPostsForLocale(locale: Locale): Promise<BlogPost[]> {
	return (await loadLocaleBlog(locale)).posts;
}

/** A locale's version of a post, by ENGLISH slug, or undefined when not published there. */
export async function getLocalizedPost(locale: Locale, enSlug: string): Promise<BlogPost | undefined> {
	return (await loadLocaleBlog(locale)).posts.find((p) => p.slug === enSlug);
}

/** Categories with at least one published post in the locale: English slug, localized name. */
export async function getCategoriesForLocale(locale: Locale): Promise<Category[]> {
	return (await loadLocaleBlog(locale)).categories;
}

/** Authors with at least one published post in the locale. Names are not translated. */
export async function getAuthorsForLocale(locale: Locale): Promise<Author[]> {
	return (await loadLocaleBlog(locale)).authors;
}

export async function getPostsByCategoryForLocale(locale: Locale, categorySlug: string): Promise<BlogPost[]> {
	return getPostsByCategoryFromPosts(await getPostsForLocale(locale), categorySlug);
}

export async function getPostsByAuthorForLocale(locale: Locale, authorSlug: string): Promise<BlogPost[]> {
	return getPostsByAuthorFromPosts(await getPostsForLocale(locale), authorSlug);
}

/** Lazy loader of a post body in a locale (English: getPostComponentLoader). */
export function getPostComponentLoaderForLocale(
	locale: Locale,
	enSlug: string
): (() => Promise<unknown>) | undefined {
	if (locale === 'en') return getPostComponentLoader(enSlug);
	return translatedComponentLoaders[`../../content/blog/${locale}/${enSlug}.svx`];
}
