import { describe, it, expect } from 'vitest';

/**
 * Regression guard for the `hashed-package-image-variants` change.
 *
 * Before this change, package thumb/mobile/desktop variants were referenced either by
 * string-replacing the base `<slug>.webp` path (`pkg.image.replace('.webp', '-thumb.webp')`)
 * or, on the equipment page, as a hardcoded literal (`/images/packages/mice-mobile.webp`).
 * Both patterns point at `static/images/packages/`, which loses the Cloudflare adapter's
 * autogenerated immutable cache header. This guard fails the suite if either pattern ever
 * reappears anywhere under `src/**`, protecting the hashed-import helper going forward.
 *
 * Sources are read with `import.meta.glob` + `?raw` (text scanning, safe for source code),
 * matching the existing convention in `no-hardcoded-prices.test.ts`.
 */

const sources = import.meta.glob('../../**/*.{ts,svelte}', {
	query: '?raw',
	import: 'default',
	eager: true
}) as Record<string, string>;

/**
 * Files allowed to contain the legacy-looking patterns, with the reason why.
 *
 * Matched by path suffix, same rationale as `no-hardcoded-prices.test.ts`: Vite returns
 * sibling modules as `./x.ts` but distant ones as `../../lib/...`.
 */
const ALLOWLIST = [
	// Constructs the `${slug}-${variant}.webp` key template internally; not a literal.
	'lib/assets/package-images.ts',
	// This file itself documents the patterns it forbids.
	'no-legacy-package-image-literals.test.ts'
];

const REPLACE_PATTERN = /\.replace\(\s*['"]\.webp['"]\s*,\s*['"]-(thumb|mobile|desktop)\.webp['"]\s*\)/;
const LITERAL_PATTERN = /\/images\/packages\/[\w-]+-(thumb|mobile|desktop)\.webp/;

const scanned = Object.entries(sources)
	.map(([path, contents]) => [path.replace(/^(\.\.\/)+/, '').replace(/^\.\//, ''), contents] as const)
	.filter(([path]) => !ALLOWLIST.some((allowed) => path.endsWith(allowed)));

describe('no legacy static package image variant references outside the helper', () => {
	it.each(scanned.map(([path]) => path))('%s references no legacy package image variant path', (path) => {
		const contents = scanned.find(([p]) => p === path)?.[1] ?? '';

		expect(
			REPLACE_PATTERN.test(contents),
			`${path} derives a package image variant via string replace. ` +
				`Use packageImageVariant() from $lib/assets/package-images instead.`
		).toBe(false);

		expect(
			LITERAL_PATTERN.test(contents),
			`${path} hardcodes a literal static/ package image variant path. ` +
				`Use packageImageVariant() (or MICE_EQUIPMENT_PAGE_IMAGE) from $lib/assets/package-images instead.`
		).toBe(false);
	});

	it('scans a meaningful number of files', () => {
		expect(scanned.length).toBeGreaterThan(50);
	});

	it('would actually catch a violation of each pattern', () => {
		expect(REPLACE_PATTERN.test("pkg.image.replace('.webp', '-thumb.webp')")).toBe(true);
		expect(LITERAL_PATTERN.test('/images/packages/mice-mobile.webp')).toBe(true);
		expect(REPLACE_PATTERN.test("pkg.image.replace('.svx', '.md')")).toBe(false);
		expect(LITERAL_PATTERN.test('/images/packages/mice.webp')).toBe(false);
	});
});
